import { LanguageCode, Translation, CardData } from './types';
import { Gamepad2, BookOpen, Cpu } from 'lucide-react';

export const LANGUAGES = [
  { code: LanguageCode.EN, label: 'English', flag: '🇺🇸' },
  { code: LanguageCode.HE, label: 'עברית', flag: '🇮🇱' },
  { code: LanguageCode.ZH, label: '中文', flag: '🇨🇳' },
  { code: LanguageCode.HI, label: 'हिन्दी', flag: '🇮🇳' },
  { code: LanguageCode.RU, label: 'Русский', flag: '🇷🇺' },
  { code: LanguageCode.DE, label: 'Deutsch', flag: '🇩🇪' },
  { code: LanguageCode.ES, label: 'Español', flag: '🇪🇸' },
  { code: LanguageCode.FR, label: 'Français', flag: '🇫🇷' },
];

export const TRANSLATIONS: Record<LanguageCode, Translation> = {
  [LanguageCode.EN]: {
    title: "Noam Gold",
    subtitle: "Explore the digital universe of Noam Gold",
    games: "Games",
    learn: "Learn",
    tech: "Tech",
    gamesDesc: "Dive into immersive and fun gaming experiences.",
    learnDesc: "Expand your mind with educational resources.",
    techDesc: "Discover the latest in technology and innovation.",
    visit: "Visit Website",
    footerRights: "Noam Gold 2025",
    sendFeedback: "Send Feedback",
    share: "Share",
    copied: "URL Copied!",
    language: "Language",
  },
  [LanguageCode.HE]: {
    title: "נועם גולד",
    subtitle: "חקור את היקום הדיגיטלי של נועם גולד",
    games: "משחקים",
    learn: "לימודים",
    tech: "טכנולוגיה",
    gamesDesc: "צלול לתוך חוויות משחק מהנות וסוחפות.",
    learnDesc: "הרחב את אופקיך עם משאבים חינוכיים.",
    techDesc: "גלה את החידושים האחרונים בטכנולוגיה.",
    visit: "בקר באתר",
    footerRights: "נועם גולד 2025",
    sendFeedback: "שלח משוב",
    share: "שתף",
    copied: "הקישור הועתק!",
    language: "שפה",
  },
  [LanguageCode.ZH]: {
    title: "Noam Gold",
    subtitle: "探索 Noam Gold 的数字宇宙",
    games: "游戏",
    learn: "学习",
    tech: "科技",
    gamesDesc: "沉浸在有趣的游戏体验中。",
    learnDesc: "利用教育资源拓展您的思维。",
    techDesc: "探索最新的科技与创新。",
    visit: "访问网站",
    footerRights: "Noam Gold 2025",
    sendFeedback: "发送反馈",
    share: "分享",
    copied: "链接已复制！",
    language: "语言",
  },
  [LanguageCode.HI]: {
    title: "Noam Gold",
    subtitle: "Noam Gold के डिजिटल ब्रह्मांड का अन्वेषण करें",
    games: "खेल",
    learn: "सीखें",
    tech: "तकनीक",
    gamesDesc: "मजेदार गेमिंग अनुभवों में गोता लगाएँ।",
    learnDesc: "शैक्षिक संसाधनों के साथ अपने ज्ञान का विस्तार करें।",
    techDesc: "नवीनतम तकनीक और नवाचार की खोज करें।",
    visit: "वेबसाइट पर जाएं",
    footerRights: "Noam Gold 2025",
    sendFeedback: "प्रतिक्रिया भेजें",
    share: "साझा करें",
    copied: "URL कॉपी किया गया!",
    language: "भाषा",
  },
  [LanguageCode.RU]: {
    title: "Noam Gold",
    subtitle: "Исследуйте цифровую вселенную Noam Gold",
    games: "Игры",
    learn: "Учеба",
    tech: "Технологии",
    gamesDesc: "Погрузитесь в захватывающий мир игр.",
    learnDesc: "Расширяйте кругозор с образовательными ресурсами.",
    techDesc: "Откройте для себя новейшие технологии.",
    visit: "Посетить сайт",
    footerRights: "Noam Gold 2025",
    sendFeedback: "Отправить отзыв",
    share: "Поделиться",
    copied: "Ссылка скопирована!",
    language: "Язык",
  },
  [LanguageCode.DE]: {
    title: "Noam Gold",
    subtitle: "Entdecke das digitale Universum von Noam Gold",
    games: "Spiele",
    learn: "Lernen",
    tech: "Technik",
    gamesDesc: "Tauche ein in spannende Spielerlebnisse.",
    learnDesc: "Erweitere dein Wissen mit Bildungsressourcen.",
    techDesc: "Entdecke die neuesten Technologien und Innovationen.",
    visit: "Webseite besuchen",
    footerRights: "Noam Gold 2025",
    sendFeedback: "Feedback senden",
    share: "Teilen",
    copied: "URL kopiert!",
    language: "Sprache",
  },
  [LanguageCode.ES]: {
    title: "Noam Gold",
    subtitle: "Explora el universo digital de Noam Gold",
    games: "Juegos",
    learn: "Aprender",
    tech: "Tecnología",
    gamesDesc: "Sumérgete en experiencias de juego divertidas.",
    learnDesc: "Expande tu mente con recursos educativos.",
    techDesc: "Descubre lo último en tecnología e innovación.",
    visit: "Visitar sitio",
    footerRights: "Noam Gold 2025",
    sendFeedback: "Enviar comentarios",
    share: "Compartir",
    copied: "¡URL copiada!",
    language: "Idioma",
  },
  [LanguageCode.FR]: {
    title: "Noam Gold",
    subtitle: "Explorez l'univers numérique de Noam Gold",
    games: "Jeux",
    learn: "Apprendre",
    tech: "Tech",
    gamesDesc: "Plongez dans des expériences de jeu immersives.",
    learnDesc: "Développez votre esprit avec des ressources éducatives.",
    techDesc: "Découvrez les dernières technologies et innovations.",
    visit: "Visiter le site",
    footerRights: "Noam Gold 2025",
    sendFeedback: "Envoyer des commentaires",
    share: "Partager",
    copied: "URL copiée !",
    language: "Langue",
  },
};

export const CARDS: CardData[] = [
  {
    id: 'games',
    titleKey: 'games',
    descKey: 'gamesDesc',
    url: 'https://noam-gold-games.vercel.app/',
    icon: 'gamepad',
  },
  {
    id: 'learn',
    titleKey: 'learn',
    descKey: 'learnDesc',
    url: 'https://learnandfun.vercel.app',
    icon: 'book',
  },
  {
    id: 'tech',
    titleKey: 'tech',
    descKey: 'techDesc',
    url: 'https://learnht.vercel.app',
    icon: 'cpu',
  },
];

export const getIcon = (type: string, className?: string) => {
  switch (type) {
    case 'gamepad': return <Gamepad2 className={className} />;
    case 'book': return <BookOpen className={className} />;
    case 'cpu': return <Cpu className={className} />;
    default: return null;
  }
};